name: Lizard Code Complexity Analysis

on:
  push:
    branches:
      - main

jobs:
  lizard-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        CCN: 3
